name: sahabatsenja_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.0
  shared_preferences: ^2.2.2
  firebase_auth: ^4.18.0
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  url_launcher: ^6.1.11
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0
  provider: ^6.1.1
  google_fonts: ^6.3.0
  http: ^1.1.0
  flutter_local_notifications: ^17.0.0
  intl: ^0.20.2
  flutter_keyboard_visibility: ^6.0.0
  webview_flutter: ^4.4.4
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_login.png"
  adaptive_icon_background: "#FFFFFF"
flutter:
  uses-material-design: true

  assets:
    - assets/images/login.jpeg
    - assets/images/logo_login.png
    - assets/images/google.png
    - assets/images/home_gambar.jpeg
fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700